dist: xenial
language: c
addons:
    apt:
        packages:
            - libavutil-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libfftw3-dev
script:
    - cmake . && cmake --build .
    - make test
compiler:
    - gcc
    - clang
