dist: xenial
language: c
addons:
    apt:
        packages:
            - libavutil-dev
            - libavcodec-dev
            - libavformat-dev
            - libswresample-dev
            - libfftw3-dev
script:
    - mkdir build && cd build && cmake .. && cmake --build .
    - make CTEST_OUTPUT_ON_FAILURE=1 test
compiler:
    - gcc
    - clang
