[package]
name = "bliss-rs"
version = "0.1.0"
authors = ["Polochon-street <polochonstreet@gmx.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
build-ffmpeg = ["ffmpeg4/build"]

[dependencies]
# TODO set proper deps
ripemd160 = "0.9.0"
ndarray-npy = "0.5.0"
ndarray = "*"
ndarray-stats = "*"
rustfft = "4.0.0"
realfft = "*"
num-complex = "0.3.0"
crossbeam = "*"

[dependencies.aubio-rs]
git = "https://github.com/katyo/aubio-rs"

[dependencies.aubio-lib]
git = "https://github.com/Polochon-street/aubio-rs"
optional = true
branch = "fix-python-version"

[dependencies.ffmpeg4]
# Like this until https://github.com/bacek/rust-ffmpeg4/pull/5 is merged
git = "https://github.com/Polochon-street/rust-ffmpeg4"
branch = "fix-flush-resampling-context"
version = "0.4.3"
