[package]
name = "bliss-rs"
version = "0.1.0"
authors = ["Polochon-street <polochonstreet@gmx.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
build-ffmpeg = ["ffmpeg4/build"]

[dependencies]
ripemd160 = "*"

[dependencies.aubio-rs]
git = "https://github.com/Polochon-street/aubio-rs"
branch = "add-some-utils"

[dependencies.aubio-lib]
git = "https://github.com/Polochon-street/aubio-rs"
branch = "add-some-utils"
optional = true

[dependencies.ffmpeg4]
# Like this until https://github.com/bacek/rust-ffmpeg4/pull/5 is merged
git = "https://github.com/Polochon-street/rust-ffmpeg4"
branch = "fix-flush-resampling-context"
