name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Packages
      run: sudo apt-get install build-essential yasm libavutil-dev libavcodec-dev libavformat-dev libavfilter-dev libavfilter-dev libavdevice-dev libswresample-dev libfftw3-dev libaubio-dev libaubio5 ffmpeg
    - name: Build
      working-directory: ./bliss-rs
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./bliss-rs
      run: cargo test --verbose
